dist: focul

language: python

sudo: enabled

python:
  - "3.6"
  - "3.7"
  - "3.8"
  
branches:
  only:
    - test
jobs:
  include:
    - os: osx
      osx_image: xcode11.2
      compiler: clang
      language: shell
      name: "Mac: Serial"
      env: USE_CUDA_PARALLEL=00

env:
  - USE_CUDA_PARALLEL="00"
  - USE_CUDA_PARALLEL="10"
  - USE_CUDA_PARALLEL="01"
  - USE_CUDA_PARALLEL="11"      

# command to install dependencies
before_install:
  - >
    if [ "${USE_CUDA_PARALLEL}" = "11" ] || [ "${USE_CUDA_PARALLEL}" = "10" ]; then
    ./add_cuda.sh; fi
  - ls -l /usr/local/

install:
  - pip install -r requirements.txt

script:
  - echo $USE_CUDA_PARALLEL
  - echo "Done"
  - python --version

