os: linux
dist: focal

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  
branches:
  only:
    - test
jobs:
   include:
     - stage: prep
       os: linux
       dist: focal
       env: CUDA=NO
            MPI=NO
       script:
          - ./add_dummy.sh
          - pip install -r requirements.txt
          - echo "Done"	  

     - os: linux
       dist: focal
       env: CUDA=NO
            MPI=YES
       script:
          - ./add_dummy.sh
          - pip install -r requirements.txt
          - echo "Done"	  
       

     - os: linux
       dist: focal
       env: CUDA=YES
            MPI=NO
       script:
          - ./add_cuda.sh
          - pip install -r requirements.txt
          - echo "Done"	  
       
     - os: linux
       dist: focal
       env: CUDA=YES
            MPI=YES
       script:
          - ./add_cuda.sh
          - pip install -r requirements.txt
          - echo "Done"	  


