language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  
branches:
  only:
    - test
#env:
#  - USE_CUDA_PARALLEL=00
#  - USE_CUDA_PARALLEL=10
#  - USE_CUDA_PARALLEL=01
#  - USE_CUDA_PARALLEL=11      

# command to install dependencies
before_install:
  #-if: env(USE_CUDA_PARALLEL) = 00
  #   script:
  #      - add_dummy.shzgxs
  - add_dummy.sh

install:
  - pip install -r requirements.txt

script:
  - echo $USE_CUDA_PARALLEL
  - echo "Done"

