os: linux
dist: focal

language: python

branches:
  only:
    - test
jobs:
   include:
     - stage: prep
       os: linux
       dist: focal
       python: ["3.6", "3.7", "3.8"]       
       env: CUDA=NO
            MPI=NO
       script:
          - ./add_dummy.sh
          - pip install -r requirements.txt
          - echo "Done"	  

     - os: linux
       dist: focal     
       python: ["3.6", "3.7", "3.8"]     
       env: CUDA=NO
            MPI=YES
       script:
          - ./add_dummy.sh
          - pip install -r requirements.txt
          - echo "Done"	  
       

     - os: linux
       dist: focal
       python: ["3.6", "3.7", "3.8"]              
       env: CUDA=YES
            MPI=NO
       script:
          - ./add_cuda.sh
          - pip install -r requirements.txt
          - echo "Done"	  
       
     - os: linux
       dist: focal
       python: ["3.6", "3.7", "3.8"]              
       env: CUDA=YES
            MPI=YES
       script:
          - ./add_cuda.sh
          - pip install -r requirements.txt
          - echo "Done"	  


