language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  
branches:
  only:
    - test
env:
  - USE_CUDA_PARALLEL=00
  - USE_CUDA_PARALLEL=10
  - USE_CUDA_PARALLEL=01
  - USE_CUDA_PARALLEL=11      

#jobs:
#  include:
#    - name: CUDA 10
#      env:
#      - CUDA=10.1.105-1
#      - CUDA_SHORT=10.1
#      - UBUNTU_VERSION=ubuntu2004
#      - WITH_CUDA=1
#      - WITH_PARALLEL=0
#      python: 3.6
#      branch: test
#    - name: SERIAL
#      env:
#      - WITH_CUDA=0      
#      - WITH_PARALLEL=0
#      python: 3.6
#      branch: test      
#    - name: PARALLEL
#      env:
#      - WITH_CUDA=0     
#      - WITH_PARALLEL=1
#      python: 3.6
#      branch: test      

# command to install dependencies
before_install:
  -if: env(USE_CUDA_PARALLEL) = 00
     script:
        - add_dummy.sh

  - add_dummy.sh

install:
  - pip install -r requirements.txt

script:
  - echo $USE_CUDA_PARALLEL
  - echo "Done"

