language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
branches:
  only:
    - test
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python3 setup.py install 