dist: focul

language: python

sudo: enabled

python:
   - "3.6"
#  - "3.7"
#  - "3.8"

addons:
  apt:
     packages:
       # GCC 4.9
       # - g++-4.9
       # MPICH
       - mpich
       - libmpich-dev
       # OpenMPI
       # - openmpi-bin
       # - libopenmpi-dev
       
branches:
  only:
    - test
jobs:
  include:
    - os: osx
      osx_image: xcode11.2
      compiler: clang
      language: shell
      name: "Mac: Serial"
      env: USE_CUDA_PARALLEL=00 

env:
  - USE_CUDA_PARALLEL="00"    # serial
#  - USE_CUDA_PARALLEL="10"    # cuda
  - USE_CUDA_PARALLEL="01"    # parallel
#  - USE_CUDA_PARALLEL="11"    # parallel + cuda  

# command to install dependencies
before_install:
  - >
    if [ "${USE_CUDA_PARALLEL}" = "11" ] || [ "${USE_CUDA_PARALLEL}" = "10" ]; then
    ./add_cuda.sh;
    export PATH=/usr/local/cuda-11.1/bin:$PATH;
    fi
  - >
    if [ "${USE_CUDA_PARALLEL}" = "01" ] || [ "${USE_CUDA_PARALLEL}" = "11" ]; then
    which mpicc;
    pip3 build mpi4py CC=mpicc CXX=mpicxx;    
    pip3 install mpi4py;
    fi
  - ls -l /usr/local/

install:
  - pip install -r requirements.txt

script:
  - echo $USE_CUDA_PARALLEL
  - echo $PATH
  - >
    if [ "${USE_CUDA_PARALLEL}" = "11" ] || [ "${USE_CUDA_PARALLEL}" = "10" ]; then  
    which nvcc;
    fi
  - >
    if [ "${USE_CUDA_PARALLEL}" = "11" ] || [ "${USE_CUDA_PARALLEL}" = "01" ]; then  
    which mpicc;
    fi
  - echo "Done"
  - python3 --version

